name: Visa Data Auto-Updater
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: pip install pandas requests beautifulsoup4
        
      - name: Run Scraper
        run: python main.py
        
      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          # Agar koi changes hain tabhi commit karein
          if [[ -n $(git status -s) ]]; then
            git add data/master_visa_data.csv
            git commit -m "Automated Visa Data Update"
            git push origin main
          else
            echo "No changes to commit"
          fi